# Generated by Django 6.0.1 on 2026-02-09 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_label', models.CharField(max_length=255)),
                ('end_label', models.CharField(max_length=255)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('video_url', models.URLField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('is_official', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
