# Generated by Django 6.0.1 on 2026-02-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('start_time', models.PositiveIntegerField(help_text='Start time in seconds')),
                ('end_time', models.PositiveIntegerField(help_text='End time in seconds')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='paths.path')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('path', 'step_number')},
            },
        ),
    ]
