# Generated by Django 6.0.1 on 2026-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_path_start_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='end_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
