# Generated by Django 6.0.2 on 2026-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_path_end_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='platform',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('web', 'Web')], default='mobile', max_length=10, null=True),
        ),
    ]
