# Generated by Django 6.0.1 on 2026-02-17 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_savedpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
