# Generated by Django 6.0.2 on 2026-02-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='path',
            name='start_point',
        ),
        migrations.AddField(
            model_name='path',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='campus',
            field=models.CharField(default='Général', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='path',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='path',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='path',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
