# Generated by Django 6.0.2 on 2026-02-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
