# Generated by Django 6.0.2 on 2026-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_path_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
