# Generated by Django 6.0.2 on 2026-02-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_path_destination_remove_path_start_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='creator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='path',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='path',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='path',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='path',
            name='video_url',
        ),
        migrations.AddField(
            model_name='path',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.path')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='admin_panel.path')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
