# Generated by Django 6.0.2 on 2026-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_path_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
