# Generated by Django 6.0.2 on 2026-02-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_creator_path_author_remove_path_admin_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='step',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='step',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
        migrations.AddField(
            model_name='path',
            name='type_parcours',
            field=models.CharField(choices=[('DESTINATION', 'Destination Simple'), ('ETAPE', 'Parcours avec Étapes'), ('VIDEO', 'Chemin Vidéo (Cloudinary)')], default='DESTINATION', max_length=20),
        ),
        migrations.AddField(
            model_name='path',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='instruction',
            field=models.TextField(default="Pas d'instruction"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='path',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='admin_panel.path'),
        ),
        migrations.AlterField(
            model_name='path',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
