# Generated by Django 6.0.2 on 2026-02-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_path_views_count_remove_step_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='type_parcours',
            field=models.CharField(choices=[('DESTINATION', 'Lieu unique (Vidéo)'), ('ETAPE', 'Parcours à étapes (Vidéo)'), ('CHEMIN', 'Itinéraire complet (Vidéo)')], default='DESTINATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='path',
            name='video_url',  
            field=models.URLField(default='http://temp.com', help_text='Lien vers la vidéo Cloudinary', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
