# Generated by Django 6.0.1 on 2026-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('admin', 'Admin')], default='participant', max_length=20),
        ),
    ]
