# Generated by Django 6.0.1 on 2026-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('admin', 'Admin'), ('etablissement', 'Etablissement')], default='participant', max_length=20),
        ),
    ]
